Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -29,15 +29,27 @@ jobs:
         
       - name: Read release notes file content
         id: read_release_notes
-        run: echo "::set-output name=body::$(cat ${{ steps.extract_release_info.outputs.body_file }})"
+        run: |
+          body_file="${{ steps.extract_release_info.outputs.body_file }}"
+          if [ -s "$body_file" ]; then
+            body=$(cat "$body_file")
+            echo "::set-output name=body::$body"
+          else
+            echo "Error: Release notes body file is empty or does not exist."
+            exit 1
+          fi
         
       - name: Create release notes file
         run: |
           version="${{ env.version }}"
           body="${{ steps.read_release_notes.outputs.body }}"
-          touch "release_notes/$version.md"
-          echo "$body" > "release_notes/$version.md"
-          echo "Release notes for version $version generated."
+          if [ -n "$body" ]; then
+            printf "%s\n\n%s\n" "## $version" "$body" > "release_notes/$version.md"
+            echo "Release notes for version $version generated."
+          else
+            echo "Error: Release notes body is empty."
+            exit 1
+          fi
 
       - name: Commit and push release notes file
         uses: stefanzweifel/git-auto-commit-action@v5
